homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  
  # Location required to calculate the time the sun rises and sets
  latitude: _REDACTED_
  longitude: _REDACTED_
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: _REDACTED_
  
  # metric for Metric, imperial for Imperial
  unit_system: metric
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: _REDACTED_
  ssl_certificate: _REDACTED_
  ssl_key: _REDACTED_

device_tracker:

ffmpeg:
  ffmpeg_bin: _REDACTED_

camera:
  - platform: ffmpeg
    input: _REDACTED_
    name: Hallway Camera
    ffmpeg_bin: _REDACTED_
  - platform: ffmpeg
    input: _REDACTED_
    name: Kitchen Camera
    ffmpeg_bin: _REDACTED_
  - platform: mjpeg
    mjpeg_url: _REDACTED_
    name: 3dprinter
    username: _REDACTED_
    password: _REDACTED_

digital_ocean:
  access_token: _REDACTED_

octoprint:
  host: _REDACTED_
  api_key: _REDACTED_

wemo:

switch:
  - platform: tplink
    host: _REDACTED_
    name: sofa lamp
  - platform: tplink
    host: _REDACTED_
    name: fireplace
  - platform: digital_ocean                                               
    droplets:                                                             
      - '_REDACTED_' 

nest:
  client_id: _REDACTED_
  client_secret: _REDACTED_

climate:
  platform: nest

media_player:
  - platform: kodi
    host: _REDACTED_
  - platform: sonos
  - platform: webostv

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

binary_sensor:                                                                  
  - platform: digital_ocean                                                     
    droplets:                                                                   
      - '_REDACTED_'  

# Weather Prediction
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - windDirection
      - humidity
      - fog
      - cloudiness
# Removed as slowed the system down
#  - platform: speedtest
#    monitored_conditions:
#      - ping
#      - download
#      - upload
  - platform: nest
    monitored_conditions:
      - 'temperature'
      - 'humidity'
  - platform: miflora
    mac: _REDACTED_
    name: Hallway plant
    force_update: false
    median: 1
    monitored_conditions:
      - moisture
      - light
      - temperature
      - battery
  - platform: miflora
    mac: _REDACTED_
    name: Living room plant
    force_update: false
    median: 1
    monitored_conditions:
      - moisture
      - light
      - temperature
      - battery
  - platform: miflora
    mac: _REDACTED_
    name: Dining room plant
    force_update: false
    median: 1
    monitored_conditions:
      - moisture
      - light
      - temperature
      - battery
  - platform: rest
    resource: _REDACTED_
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'Bedroom Lux'
    scan_interval: 2
  - platform: rest
    resource: _REDACTED_
    value_template: '{{ value_json.config.tholddark }}'
    unit_of_measurement: Lux
    name: 'Bedroom Min Lux'
    scan_interval: 2
    
automation: !include automation.yaml

group: !include groups.yaml

light:
  - platform: piglow

input_boolean:
  arm_alarm_switch:
    name: Armed
    initial: off
    icon: mdi:lock-outline

shell_command:
  arm_alarm: _REDACTED_
  disarm_alarm: _REDACTED_
  
